version: "3.9"

services:
  database:
    build:
      context: ./
      dockerfile: ./docker/database/Dockerfile.dev
      args:
        - version=${DB_VERSION}
    restart: on-failure
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - database_data:/var/lib/mysql

  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile.dev
      args:
        - version=${BACKEND_PHP_VERSION}
    env_file:
      - ./.env
    volumes:
      - "./src/backend:/var/www/html"
      - /var/www/html/vendor
    ports:
      - "${BACKEND_PORT}:80"
    restart: on-failure
    depends_on:
      - database
    command: >
      sh -c "composer install && php artisan migrate:fresh && php artisan db:seed && php artisan serve --port=80 --host=0.0.0.0"

  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile.dev
      args:
        - version=${FRONTEND_NODE_VERSION}
    env_file:
      - ./.env
    volumes:
      - "./src/frontend:/app"
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:3000"
    restart: on-failure
    depends_on:
      - backend
    stdin_open: true
    command: >
      sh -c "npm start"

volumes:
  database_data:
    driver: local
