version: "3.9"
services:
  database:
    build:
      context: ./docker/database
      dockerfile: Dockerfile.dev
      args:
        - version=${BACKEND_MARIADB_VERSION}
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${BACKEND_MARIADB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile.dev
      args:
        - version=${BACKEND_PHP_VERSION}
    environment:
      - XDEBUG_CONFIG= remote_port=${XDEBUG_PORT} remote_log_level=10 remote_host=host.docker.internal idekey=VSCODE remote_connect_back=0
    volumes:
      - "./src:/var/www/html"
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "${BACKEND_PORT}:80"
    restart: on-failure
    depends_on:
      - database
    command: >
      sh -c "php -S 0.0.0.0:80 -t public"
volumes:
  database_data:
    driver: local
