ARG version
FROM node:${version}
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./src/frontend/package.json ./
COPY ./src/frontend/package-lock.json ./
RUN npm install
RUN npm install react-scripts@4.0.3 -g